end with failure workflow step on failure

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,3 +23,5 @@ jobs:
       - name: Error tests workflow
         run: |
           echo 'The triggering workflow failed'
+          echo 'This workflow now ends with failure too'
+          exit 1
